### ISSUE TITLE
Problem with composer require

### ISSUE THREAD

**Issue by PhoxPHP** [rinvex/subscriptions#13]
Hi,

I am trying to install this package and use it with a laravel 5.5 project but i get this error instead:

  Problem 1
    - Installation request for rinvex/subscriptions ^0.0.2 -> satisfiable by rinvex/subscriptions[v0.0.2].
    - rinvex/subscriptions v0.0.2 requires rinvex/cacheable dev-develop -> satisfiable by rinvex/cacheable[dev-develop] but these conflict with your requirements or minimum-stability.

Is there a propery way of installing it?
Regards
Peter

**Comment by Omranic** [comment]
Yes, you should use *dev-develop* and it will work smoothly for you. Once this is tagged as stable, you can use then *master* branch. Pl ads feel free to reopen this issue if you need further assistance:)
