### ISSUE TITLE
Can't create a plan. Trait does not exist.

### ISSUE THREAD

**Issue by Peter2962** [rinvex/subscriptions#14]
Hi There,

I am trying to create a plan but i keep getting this error: 
PHP Fatal error:  Trait 'Rinvex\Support\Traits\HasTranslations' not found.

I see that the trait does not exist. Any way to fix?

**Comment by Omranic** [comment]
Mentioned traits are available on **develop** branch. All packages that's still not yet tagged should be used on the develop branch only as it's the most updated & even more stable than master. This changes when we tag v1.x releases, hopefully soon!

**Comment by Peter2962** [comment]
Thank you 👍
