### ISSUE TITLE
Redirect loop on plan creation

### ISSUE THREAD

**Issue by Peter2962** [rinvex/subscriptions#15]
I installed this package and setup everything as instructed but when i try to create a new plan, i get a redirect loop error. The code i am running is as shown below:
		```
$plan = app('rinvex.subscriptions.plan')->create([
			'name' => 'Pro',
			'description' => 'Pro plan',
			'price' => 9.99,
			'invoice_period' => 1,
			'invoice_interval' => 'month',
			'trial_period' => 15,
			'trial_interval' => 'd',
			'sort_order' => 1,
			'currency' => 'USD',
		]);
```
Thanks.

**Comment by Omranic** [comment]
Which branch you're using? Make sure it's the **develop** branch please since it's the most up to date for this under-development package. Let me know if that didn't fix your issue..

**Comment by Peter2962** [comment]
Yes i am using develop branch. Thank you.

**Comment by Omranic** [comment]
Ok, let me test your code sample within minutes & get back to you..

**Comment by Peter2962** [comment]
Okay thank you.

**Comment by Peter2962** [comment]
And i'm using it with laravel 5.5. Thanks.

**Comment by Omranic** [comment]
Tested & confirmed to be an issue with the sample code in our docs, here's the correct code to use for now until we update docs and/or the package itself too:
```php
        $plan = app('rinvex.subscriptions.plan')->create([
            'name' => 'Pro',
            'description' => 'Pro plan',
            'price' => 9.99,
            'signup_fee' => 1.99,
            'invoice_period' => 1,
            'invoice_interval' => 'm',
            'trial_period' => 15,
            'trial_interval' => 'd',
            'sort_order' => 1,
            'currency' => 'USD',
        ]);
```

What changed here is the `invoice_interval` is now a char of one letter, so it's `m` instead of `month`, and `signup_fee` is required field. That's it, should work for you now :) Feel free to re-open if you've any further issues!

**Comment by Peter2962** [comment]
Okay thank you.

**Comment by Peter2962** [comment]
It works now. Thank you.
