### ISSUE TITLE
BadMethodCallException - Method 'addMs' does not exist.

### ISSUE THREAD

**Issue by Peixer** [rinvex/subscriptions#19]
I get its exception when tried subscribe an user in plan. I guess that its happen because the file Period.php not using month.

**Comment by Omranic** [comment]
All `interval` fields are now string-based that accepts (`hour`, `day`, `week`, `month`) .. You should be able to use the latest release without any issues bf8b67beaa89fbc54c6ea6a7720fab0e3dc5d8cc

**Comment by Peixer** [comment]
Thanks @Omranic
