### ISSUE TITLE
Laravel 5.5 composer require

### ISSUE THREAD

**Issue by hanc2006** [rinvex/subscriptions#21]
After the latest commit where the support for the Laravel 5.5 was dropped, how can I still use this package without update Laravel to 5.6? If I try to resolve the dependencies in many way but composer fails every time.

**Comment by Omranic** [comment]
It's easy and straight forward to upgrade to Laravel v5.5, but if you don't plan to do so feel free to fork the package and update your project's `composer.json` like so https://getcomposer.org/doc/05-repositories.md#using-private-repositories

**Comment by maximaexchen** [comment]
Is still possible to install the package on 5.5.?
I get the "conflict in requirements" error

**Comment by Omranic** [comment]
@maximaexchen you can lock your composer on `v0.0.3`
